- name: Deploy Spring Boot App Locally
  hosts: localhost
  become: yes

  tasks:
    - name: Ensure deployment directory exists
      file:
        path: /opt/student-app
        state: directory
        mode: '0755'

    - name: Copy built jar to deployment location
      copy:
        src: "{{ playbook_dir }}/../target/student-passfail-0.0.1-SNAPSHOT.jar"
        dest: /opt/student-app/student-passfail.jar
        mode: '0755'

    - name: Kill any running app (only Java process)
      shell: |
        pids=$(pgrep -f 'java -jar /opt/student-app/student-passfail.jar') || true
        if [ -n "$pids" ]; then
          echo "→ Killing PIDs: $pids"
          kill $pids || true
        else
          echo "→ No running app to kill"
        fi
      args:
        warn: false

    - name: Start Spring Boot app
      shell: |
        nohup java -jar /opt/student-app/student-passfail.jar --server.port=8888 \
          > /opt/student-app/app.log 2>&1 &
      args:
        warn: false
