- name: Deploy Spring Boot App Locally
  hosts: localhost
  become: yes

  tasks:
    - name: Ensure deployment directory exists
      file:
        path: /opt/student-app
        state: directory
        mode: '0755'

    - name: Determine the built JAR file
      set_fact:
        jar_file: "{{ lookup('fileglob', playbook_dir + '/../target/*.jar', wantlist=True)[0] }}"

    - name: Copy built jar to deployment location
      copy:
        src: "{{ jar_file }}"
        dest: /opt/student-app/student-passfail.jar
        mode: '0755'

    - name: Stop old Spring Boot process (via pidfile)
      shell: |
        if [ -f /opt/student-app/student-passfail.pid ]; then
          pid=$(cat /opt/student-app/student-passfail.pid)
          kill "$pid" || true
        fi
      args:
        executable: /bin/bash

    - name: Start Spring Boot app and record PID
      shell: |
        nohup java -jar /opt/student-app/student-passfail.jar --server.port=8888 \
          > /opt/student-app/app.log 2>&1 &
        echo $! > /opt/student-app/student-passfail.pid
      args:
        executable: /bin/bash

    - name: Wait for the app to respond on port 8888
      uri:
        url: http://localhost:8888
        status_code: 200
        retries: 30
        delay: 2
        timeout: 5
