- name: Deploy Spring Boot App Locally
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure deployment directory exists
      file:
        path: /opt/student-app
        state: directory
        mode: '0755'

    - name: Copy built jar to deployment location
      copy:
        src: "{{ playbook_dir }}/../target/student-passfail-0.0.1-SNAPSHOT.jar"
        dest: /opt/student-app/student-passfail.jar
        mode: '0755'

    - name: Stop old Spring Boot process (via pidfile)
      shell: |
        if [ -f /opt/student-app/student-passfail.pid ]; then
          pid=$(cat /opt/student-app/student-passfail.pid)
          if kill -0 "$pid" 2>/dev/null; then
            echo "→ Killing old app (PID $pid)"
            kill "$pid" || true
          else
            echo "→ No process running at PID $pid"
          fi
        else
          echo "→ No pidfile found, nothing to kill"
        fi
      args:
        executable: /bin/bash

    - name: Start Spring Boot app and record PID
      shell: |
        nohup java -jar /opt/student-app/student-passfail.jar --server.port=8888 \
          > /opt/student-app/app.log 2>&1 &
        echo $! > /opt/student-app/student-passfail.pid
      args:
        executable: /bin/bash
